name: safe_exam_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.0.0
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  chewie: ^1.7.1
  flutter_pdfview: ^1.3.2
  wakelock_plus: ^1.1.4
  window_manager: ^0.3.8
  google_fonts: ^6.1.0
  intl: ^0.18.1
  lottie: ^3.1.0
  audioplayers: ^6.0.0
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/splash.json
    - assetsimages/
    - assetsmp3/
